version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: terraformDatabase
      POSTGRES_USER: LuizNazareth
      POSTGRES_PASSWORD: Lg160103*
      POSTGRES_HOST: terraform-rds-postgres.cwx8awcq8n7y.us-east-1.rds.amazonaws.com
